//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int ID { get; set; }
        public string TenNhanVien { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Email { get; set; }
        public Nullable<int> IDLoaiNhanVien { get; set; }
        public string ChucVu { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
